version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/booking_db
      PAYMENT_GATEWAY_API_KEY: your_payment_gateway_api_key
      SECRET_KEY: supersecretkey
    depends_on:
      - db

volumes:
  postgres_data:
